name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Permissions moment
      run: chmod +x ./gradlew
    - name: Install robot toolchain
      run: ./gradlew installRoboRioToolchain
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: List files
      run: ls ./
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: artifacts

        # A file, directory or wildcard pattern that describes what to upload
        # Required.
        path: build/exe/*
